---
- name: Check if Secret Exists
  become: yes
  ansible.builtin.stat:
    path: "{{ path }}"
  register: secret_stat_result

- name: "Create Secret {{ path }}"
  become: yes
  ansible.builtin.copy:
    dest: "{{ path }}"
    content: "{{ secret }}"
    owner: "root"
    group: "root"
    mode: 0600
  when: not secret_stat_result.stat.exists
