---
- name: Maybe create user
  hosts: all
  # gather_facts must be disabled here to use this role
  gather_facts: no
  become: true
  roles:
    - bootstrap
    - geerlingguy.pip
    - maybecreateuser

  tasks:
    - name: reset ssh connection
      meta: reset_connection

- name: Lockdown
  hosts: all
  become: true
  roles:
    - lockdown
    - pihole
