---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  roles:
    - initialuser
  tags:
    - base

- name: pibase
  hosts: sbcs
  roles:
    - pi-base
  tags:
    - base

- name: Pihole
  hosts: bpi1
  roles:
    - pihole
  tags: pihole

- name: gatewaypi1
  hosts: gatewaypi1
  roles:
    - role: cloudflare_dyndns
      tags: ddns
    - role: backup
      tags: borg
    - role: fanshim
      tags: fanshim
    - role: dockerdaemon
      tags: docker
    - role: traefik_master
      tags: traefik
