---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  become: true
  roles:
    - maybecreateuser # gather_facts must be disabled here to use this role
    - bootstrap
  tasks:
    - name: reset ssh connection
      meta: reset_connection

- name: Lockdown
  hosts: all
  become: true
  roles:
    - lockdown

- name: Pihole
  hosts: bpi1
  become: true
  roles:
    - pihole
