---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  become: true
  roles:
    - maybecreateuser # gather_facts must be disabled here to use this role

- name: Basic Provision
  hosts: all
  become: true
  roles:
    - role: bootstrap
      tags:
        - bootstrap
    - role: lockdown
      tags:
        - lockdown

- name: Pihole
  hosts: pihole1
  become: true
  roles:
    - pihole
