---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  become: true
  roles:
    - maybecreateuser # gather_facts must be disabled here to use this role
    - bootstrap
  tasks:
    - name: reset ssh connection
      meta: reset_connection

- name: Lockdown
  hosts: all
  roles:
    - role: lockdown
      become: true # Run as Root
      tags:
        - lockdown

- name: Pihole
  hosts: pihole
  become: true
  roles:
    - pihole
