---
- name: ensure Pip Packages installed
  become: yes
  ansible.builtin.import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: jsondiff
      - name: pyyaml
      - name: docker-compose

- name: ensure Docker Installed
  become: yes
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_install_compose_plugin: true

- name: reset ssh connection
  meta: reset_connection
