---
- name: Clone Fanshim Git
  become: yes
  ansible.builtin.git:
    repo: https://github.com/pimoroni/fanshim-python.git
    dest: /opt/fanshim
    version: master

- name: Populate service facts
  become: yes
  ansible.builtin.service_facts:

- name: Install Fanshim Service
  become: yes
  ansible.builtin.shell:
    cmd: cd /opt/fanshim/examples && ./install-service.sh
  when: "'pimoroni-fanshim.service' not in ansible_facts.services"
  changed_when: true
