---
- name: Ensure DDclient installed
  become: yes
  ansible.builtin.apt:
    name:
      - ddclient
      - libjson-pp-perl
      - libio-socket-ssl-perl
    state: present

- name: Ensure Ddclinet config
  become: yes
  ansible.builtin.copy:
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: 0600
    content: "{{ ddclient_config }}"
  notify: Restart ddclient

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
