---
- name: Install Borgbackup
  package:
    name:
      - borgbackup
      - jq
    state: present

- name: ensure Pip Packages installed
  pip:
    name: borgmatic

- name: "Create Backup User"
  become: yes
  user:
    name: "borgbackup"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    state: present
    groups: "{{ borg_user_groups }}"
  register: borgbackup_user

- name: Borgmatic Config Folder
  become: true
  file:
    path: "/etc/borgmatic"
    state: directory
    owner: "borgbackup"
    group: "borgbackup"
    mode: 0770

- name: Template Borgmatic Config
  become: yes
  template:
    src: borgmatic-config.yml.j2
    dest: /etc/borgmatic/config.yaml
    owner: "borgbackup"
    group: "borgbackup"
    mode: 0660

- name: Set Backup Cron Job
  become: yes
  cron:
    name: "Borg Backup"
    minute: "47"
    hour: "4"
    job: "PATH=$PATH:/usr/bin:/usr/local/bin borgmatic --verbosity 1 --syslog-verbosity 1"
  when: backup_cron
