---
- name: restart ssh
  block:
    - name: Restart SSHd
      service:
        name: sshd
        state: restarted
    - name: reset ssh connection
      meta: reset_connection

- name: restart ufw
  community.general.ufw:
    state: reloaded
