---
- name: update trusted ca debian
  become: true
  command: /usr/sbin/update-ca-certificates
  when: ansible_os_family == "Debian"

- name: Reboot System
  reboot:
    reboot_timeout: 1800

- name: restart ssh
  service:
    name: sshd
    state: restarted
  register: restart_result

- name: restart ufw
  community.general.ufw:
    state: reloaded

- name: reset ssh connection # To enforce group changes
  meta: reset_connection
  ignore_errors: True
  when: restart_result is not defined
