---
- name: Disable SSH Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify:
    - restart ssh

- name: Disable SSH Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh

- name: Make sure SSH Agent forwarding also works on sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
    state: present
    backup: yes
  notify: reset ssh connection
