---
- name: Install Ufw
  package:
    name: ufw
    state: present

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Set SSH limiting in UFW
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: restart ufw

- name: Allow TCP Ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
  notify: restart ufw

- name: Allow Additional Ports
  when: lockdown_extra_allow_ports is defined
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ lockdown_extra_allow_ports }}"
  notify: restart ufw

- name: Deny Other Ports
  community.general.ufw:
    policy: deny
  notify: restart ufw
