---
- name: Basic Setup
  become: yes
  import_tasks: basic-setup.yml

- name: Mount Drives
  become: yes
  import_tasks: mount-drives.yml

- name: Lockdown SSH
  become: yes
  import_tasks: lockdown-ssh.yml

- name: Lockdown UFW
  become: yes
  import_tasks: lockdown-ufw.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
