---
- name: Basic Setup
  ansible.builtin.import_role:
    name: joshkreud.base

- name: Mount Drives
  become: yes
  ansible.builtin.import_tasks: mount-drives.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
