---
- name: Mount up device by UUID
  when: mount_drives is defined
  ansible.posix.mount:
    path: "{{ item.path }} "
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default('defaults') }}"
    state: present
  loop: "{{ mount_drives }}"
