---
- name: create pihole directory
  ansible.builtin.file:
    path: /etc/pihole
    state: directory

- name: Check Pihole Installed
  ansible.builtin.stat:
    path: /usr/local/bin/pihole
  register: pihole_binary

- name: Remembber Install Status
  ansible.builtin.set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists | default(false) }}"

- name: copy pihole conf
  ansible.builtin.template:
    src: pihole-setupVars.conf
    dest: /etc/pihole/setupVars.conf
  notify: Pihole reload

- name: download install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
    dest: ~/pihole-install.sh
    mode: u+rwx
  when: not pihole_installed

- name: run install script
  ansible.builtin.shell: ~/pihole-install.sh --unattended
  when: not pihole_installed
