---
- name: Install Unbound Recursive DNS
  ansible.builtin.apt:
    name: "unbound"
    state: present

- name: Template Unbound Config
  ansible.builtin.template:
    src: unbound-pihole.conf.j2
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
  notify: Restart Unbound

- name: Disable Ubound Resolved
  ansible.builtin.service:
    name: unbound-resolvconf
    state: stopped
    enabled: no
